# Chapter 4 {.unnumbered}

**이자율 (*Interest Rates*)**

파생상품과 여러 금융상품의 가치평가에 쓰이는 매우 중요한요소


## 4.1 이자율의 종류

이자율이란 돈을 빌린사람이 빌려준 사람에게 지급하는 돈에 적용되는 율로 주택담보, 예금수익률, 신용대출 등 수많은 이자율의 종류가 있습니다. 이자율에 영향을 주는 요소 중 하나로 신용위험(*Credit Risk*)가 있는데, 돈을 빌린사람이 디폴트 등으로 돈을 값지 못하게 될 위험을 말합니다. 그 위험이 클수록 이자율은 증가하게 되고, 해당 이자율과 무위험이자율 간의 차이를 신용스프레드(*Credit Spread*)라 합니다.

### Treasury Rates

T-bill, T-bond와 같은 국가가 발행한 채권에 투자할 때 얻는 수익률을 말합니다. 이 수익률은 결국 **해당 채권을 발행한 국가에 돈을 빌려주고 받는 이자율**을 의미합니다. 일반적으로 선진국의 국채가 파산할 위험은 거의 없기때문에, 무위험이자율로 여겨지곤 합니다. 그러나, 개발도상국의 국채를 생각해보면 파산위험이 0은 아니므로, 엄밀한 의미의 무위험이자율은 아닙니다.

### Overnight Rates

각국의 시중은행은 중앙은행의 정책에 따라 지급준비금이라는 형태로 일정 비율 이상의 현금을 유지해야합니다. 매일 마감작업 이후, 지급준비금이 부족한 은행은 현금이 충분한 은행으로부터 지급준비금 부족액을 다음날까지 빌리게 되는데, 이 때 적용되는 것이 1일물 금리입니다. 대표적으로 미국 연준의 경우 *federal funds rate*를 예시로 들 수 있고, 이 금리를 이용하여 이루어진 실제 은행간 거래를 거래량 가중평균하여 산출한 금리를 *effective federal funds rate*라고 합니다. 다른 예시로는 영국의 SONIA(*sterling overnight index average*), EU의 ESTER(*euro short-term rate*), 스위스의 SARON(*swiss average rate overnight*), 일본의 TONAR(*tokyo overnight average rate*)가 있으며, 우리나라는 콜금리가 대표적입니다.

### Repo rates or RP rates

연준금리나 일반적인 1일물 금리와 달리, 담보부 금리입니다. 주로 금융기관 간에 국채나 안전자산을 담보로 짧은기간 현금을 빌릴때 이용되는 금리이며, 담보가 있는 만큼 신용 기반의 1일물 금리보다 무위험에 가깝기때문에 조금 더 낮게 형성됩니다. 일반적으로 *overnight repos*가 쓰이지만, 간혹 기간이 긴 *term repos*도 사용됩니다. 대표적으로 미국의 SOFR(*secured overnight financing rate*)가 있으며, 우리나라의 신규 금리인 KOFR(*Korea overnight financing rate*)도 여기에 해당합니다.

## 4.2 Reference rates

기준금리는 금융시장에서 매우 중요한 역할을 담당합니다. 시장참가자간 돈을 빌리는 등 거래를 할 때, 기준금리에 일정 금리를 가산하는 식으로 주로 활용되기 때문에 합리적이고 공정한 방식으로 산출되는 것이 매우 중요합니다.

### Libor, London Inter Bank Offered Rates

역사적으로 매우 중요한 기준금리로서, 런던의 글로벌 은행들 간의 거래에 적용되는 금리로 1일물부터 1년물까지 존재합니다. 글로벌 은행들의 신용은 매우 높은 수준이기 때문에, 일반적으로 무위험금리의 대용치로 많이 사용되었습니다. 대게 장외파생상품 또는 다양한 금융상품에 있어 기준금리로 활용되었기 때문에, libor에 연계된 자금규모는 수백조 달러에 육박하였습니다. 그러나, 신용 기반의 금리인 점과 은행의 호가금리에 기반한다는 치명적인 단점이 있고, 2012년 이를 이용한 Libor 조작사태가 벌어지면서 기준금리의 대규모 전환을 맞이하였고, EU벤치마크법 등 다양한 논의 끝에 현재는 다른 무위험금리로 Libor를 대체하고자 하는 추세입니다.

### The New reference rates

각국은 Libor를 대체할 새로운 기준금리를 개발하였고, 상기에 서술한 KOFR, SOFR, SONIA, ESTER, SARON, TONAR 등이 여기에 해당합니다.

새로운 기준금리는 1일물 금리로 정의되며, 이를 기반으로 3개월, 6개월 등의 기간구조를 산출합니다. SOFR를 예시로 들면, n일간 SOFR금리는 다음과 같습니다.

$$[(1+r_1 \hat{d}_1)(1+r_2 \hat{d}_2)\dots(1+r_n \hat{d}_n)-1]\times \frac{360}{D}$$
$$where\;\hat{d}_i=\frac{d_i}{360},\;D=\sum d_i$$

대게 $d_i$는 1이며, 주말이나 휴일이 포함된 경우 해당 일을 가산합니다. 이러한 방식으로 산출 된 기준금리는 무위험금리로 여겨집니다. 1일물 금리를 compounding하여 산출하였고, 담보가 있거나 신용위험이 거의 없는 기관간 금리이기 때문입니다.

Libor와 새로운 기준금리의 또하나의 큰 차이점은 산출시점입니다. 3개월 Libor는 현재시점에서 *forward looking* 방식으로 산출되지만, 3개월 SOFR는 과거 3개월간 실현된 1일물 SOFR를 compounding하여 *backward looking* 방식으로 산출합니다.

### Reference rates and Credit risk

은행간 금리의 또다른 문제점은, 평소에는 파산할 위험이 거의 없지만, 금융위기같은 극단적인 상황에서는 은행도 파산할 수 있으며, 따라서 은행의 신용위험이 증가한다는 것 입니다. 이러한 경우, 무위험금리로 여겨지던 Libor금리에 은행의 신용위험이 더해지면서 실질적으로 무위험금리+신용스프레드가 적용된 Libor금리가 형성되므로 정상적인 기준금리의 역할을 할 수 없습니다.

그러나, 새로운 기준금리는 사실상 무위험금리에 해당하므로 신용위험으로 인해 기준금리가 왜곡될 문제는 없다고 봐도 무방합니다.

## 4.3 The Risk-free rate

앞선 장에서, 파생상품의 프라이싱에는 무위험 포트폴리오를 구축할 수 있고, 여기에서 무위험이자율 만큼의 수익이 발생한다는 가정을 사용하였습니다. 즉, 무위험이자율은 파생상품의 프라이싱에 매우 핵심적인 역할을 하고 있습니다. 실제로 트레이더들은 국채를 이용해서 무위험 포트폴리오를 구축하는 것이 자연스러워보이나, 현실은 그렇지 않습니다. 일반적으로 국채금리는 세금 등의 규제적인 이유로 낮게 형성되기 때문입니다.

1. 대부분의 은행이 여유자본을 활용할 때, 국채에 투자하는 일은 없고 대신 다른 무위험자산을 찾는다.
2. 미국의 경우, 대부분의 주에서 국채의 이자수익에 대한 세금혜택이 존재

따라서, 무위험이자율은 앞서 살펴본 1일물 금리를 주로 사용하게 됩니다.

## 4.4 Measuring interest rates

예금 이자에 1년간 10%의 금리가 적용된다는 것은, 이자율의 측정방법을 무엇으로 하느냐에 따라 다른 결과가 나올 수 있습니다.

1. 단리 : 100만원을 투자하고 1년 후 110만원을 돌려받으므로 10% 수익에 해당

2. 복리 : 복리 주기에 따른 중간이자를 다시 재투자하므로, 단리보다 실질이자율이 높게 됨
    - semiannually : $100\times 1.05\times 1.05=110.25$, 10.25%
    - monthly : $100\times(1+\frac{10\%}{12})^{12}=110.47$, 10.47%
    - 즉, $원금\times(1+\frac{이자율}{지급횟수})^{기간\times 지급횟수}$

3. 연속복리 : 이자를 매 순간순간 지급하고 재투자한다면,

$$원금\times(1+\frac{이자율}{지급횟수})^{기간\times 지급횟수}\rightarrow 원금\times e^{이자율\times 기간}$$
$$where\;지급횟수\rightarrow \infty$$

## 4.5 Zero-rates

**원금을 n년간 투자**할 때, 중간이자 및 옵션 없이 **만기에 원금과 이자를 일시에 정산**받는다면, 이때 적용되는 이자율은 쿠폰이 없는 채권에 투자한 것과 같으므로 zero-coupon interest rate라고 할 수 있습니다. 일반적으로 이를 *n-year spot rate* 또는 *n-year zero rate*라고 합니다.

채권에 투자할 때, 일반적으로 이표채에 투자하게되므로 5년 만기 국채를 사더라도 해당 국채의 YTM이 5년짜리 zero-rate를 의미하는 것은 아닙니다. 중간에 이자수익이 발생하기 때문입니다.($Duration\ne 5$)

 - 예시 : 5년 zero rate가 연속복리로 5%라면 5년후 수익은 $100\times e^{0.05\times 5}=128.40$

## 4.6 Bond pricing

채권의 가치평가는 채권의 만기까지 발생하는 이자와 원금을 각각 현재가치로 환산한 후 합하여 계산합니다. 여기에서, 각각의 이자와 원금을 현재가치로 할인하는데 쓰이는 이자율이 *zero rates*입니다.

|years|Zero rates|
|-----|---------:|
|0.5  |   5.0%   |
|1.0  |   5.8%   |
|1.5  |   6.4%   |
|2.0  |   6.8%   |

원금이 100$이고 쿠폰이 6%인 채권이 semiannually 이자를 지급하고, 위의 zero rates를 적용하면 채권의 가격은 다음과 같습니다.

$$3e^{-0.05\times 0.5}+3e^{-0.058\times 1.0}+3e^{-0.064\times 1.5}+103e^{-0.068\times 2.0}=98.39$$

### Bond Yield

채권의 수익률이란, 채권의 현금흐름과 현재 가격을 일치시키는 수익률을 말합니다. 즉, 상기 zero rates를 통해 구한 채권가격과 채권의 현금흐름에 단일 수익률을 적용하여 구한 현재가치가 같아지면 됩니다.

$$YTM\; y\; :\; 3e^{-y\times 0.5}+3e^{-y\times 1.0}+3e^{-y\times 1.5}+103e^{-y\times 2.0}=98.39$$

수치해석방법을 통해 y를 구하면, 약 6.76%임을 알 수 있습니다.

### Par Yield

*par yield*란, zero rates를 통해 채권가격을 산출할 때, **채권가격이 par가 되는 coupon rate**를 말합니다. 즉, 위의 예시에서 par yield는

$$\frac{c}{2}e^{-0.05\times 0.5}+\frac{c}{2}e^{-0.058\times 1.0}+\frac{c}{2}e^{-0.064\times 1.5}+(100+\frac{c}{2})e^{-0.068\times 2.0}=100(par)$$
$$c\approx 6.87\%$$

## 4.7 Determining zero rates

실제로 zero rates는 잘 알려져있지 않으므로, 국채수익률을 이용하여 zero rates를 역산하는 방식을 주로 사용합니다. 이때 사용하는 방식을 *Bootstrap method*라고 하며, 다음과 같습니다.

1. 채권은 연 2회 이자를 지급한다고 가정
2. 3개월, 6개월, 1년, 2년, 1.5년, 2년 zero rates를 구하고자 함
3. 각 만기별 국채를 통해 만기별 채권 YTM을 산출
4. 3개월 및 6개월 국채는 잔여 이자지급이 없으므로 YTM=zero-rate
5. 6개월 zero-rate와 1년만기 국채의 가격을 통해 1년 zero-rate 산출
6. 6개월 및 1년 zero-rate와 1.5년 국채가격을 통해 1.5년 zero-rate 산출
7. 같은 방법으로 2년 zero-rate 산출

## 4.8 Foward rates

선도금리란, 미래시점에 적용되는 금리를 말합니다. 예를 들어 현재시점에서 1년뒤에 1년간 적용되는 선도금리를 구한다고 가정하면, 1년 zero rate와 2년 zero rate의 관계를 통해 구할 수 있습니다.

현재시점에서 원금을 2년 zero rate에 투자한 것과 1년 zer rate + 선도금리에 투자한 포트폴리오의 수익은 동일해야 하므로,
$$100e^z_1e^f_{12}=100e^{z_2\times 2}\rightarrow f_{12}=2\times z_2=z_1$$
연속복리 수익률에서 $t_0$시점에서 $t_1\sim t_2$까지의 선도수익률 $F_{12}$을 일반화하면,
$$F_{12}=\frac{t_2\times z_2-t_1\times z_1}{t_2-t_1}$$

$$F_{12}=z_2+(z_2-z_1)\frac{t_1}{t_2-t_1}\rightarrow z+t\frac{\partial z}{\partial t}\;for\; t_2\rightarrow t_1$$

해당 극한값은 기간이 매우 짧을때 적용할 수 있는 선도수익률로, *instantaneous forward rate*라고 합니다.

### Foward rates : furthermore

*instantaneous forword rate*의 유도방법

$Let P()\; i\;  a\; present\; value\; functions,\; P(t,T)=e^{-(T-t)z_T}$

$Then,\; Forward\; rate\; F(t,T,T+\delta)=F\; is,$

$\frac{e^{\delta\times F}}{P(t,T)}=\frac{1}{P(t,T+\delta)}\Rightarrow F=\frac{1}{\delta}\ln[\frac{P(t,T)}{P(t,T+\delta)}]=-\frac{\ln[P(t,T+\delta)]-\ln[P(t,T)]}{\delta}$

$$instantaneous\; forward\; rate\; \hat{F}=-\frac{\partial}{\partial T}\ln[P(t,T)]\; where\;\delta \rightarrow 0$$

## 4.9 Forward rate agreements
FRA는 금리파생상품의 일종으로, 계약자들은 향후 특정시점에 변동금리를 현재시점의 FRA계약금리로 고정시키고 계약만기시점에 변동금리와 고정금리를 주고받는 형태의 계약입니다.

**FRA매수자**는 **변동금리를 받고 고정금리(FRA계약금리)를 주며**, 따라서 **변동금리가 향후 상승하면 유리**한 포지션입니다. 따라서 향후 **돈을 빌리고자 하는 사람**들이 사용합니다. 반대로 FRA매도자는 변동금리를 주고 고정금리를 받으므로, 금리 하락시 유리한 포지션입니다.

FRA는 옵션 등이 없는 계약이므로, 계약을 체결하는 시점에 매수자 및 매도자가 동등한 위치에서 계약을 체결합니다. 따라서 체결시점의 계약은 누군가에게 유리하게 체결되어서는 안되고, 이는 **계약의 가치가 0원**임을 의미합니다. 즉, **계약만기시점의 Forward rate가 일반적인 FRA의 계약금리**가 됩니다.

계약금리가 **Forward rate로 설정되지 않는다면, 차익거래기회가 발생**합니다. Forward rate보다 낮게 FRA계약이 체결된다면, 투자자는 FRA매수와 동시에 FRA원금만큼 Forward rate에 돈을 빌려줌으로써 Forward rate - FRA금리 만큼의 무위험차익을 얻을 수 있습니다.

## 4.10 Duration

채권의 듀레이션이란, 채권 소유자의 원금회수기간을 의미합니다. 즉, 채권이 원금(=채권가격)만큼의 현금흐름을 발생시키는데 걸리는 시간을 말합니다. 따라서 듀레이션은 채권의 각 현금흐름이 원금에서 차지하는 비율을 시간가중평균하여 산출하게 됩니다.

채권이 $c_i$만큼의 현금흐름을 발생시키고, 현재 가격은 $B$, 수익률은 $y$라고 하면 채권의 가격과 현금흐름은 $B=\sum c_ie^{-yt_i}$입니다.

이에 대한 시간가중평균인 듀레이션은 다음과 같습니다.

$$D=\frac{\sum t_ic_ie^{-yt_i}}{B}=\sum t_i[\frac{c_ie^{-yt_i}}{B}],\; \sum t_i=1$$

간단한 미분의 성질을 활용하면, $\Delta B=\frac{dB}{dy}\Delta y=-\Delta y \sum c_it_ie^{-yt_i}=-\Delta y\times B\times D$

즉, $\frac{\Delta B}{B}=-D\Delta y$를 유도할 수 있습니다.

이는 채권가격의 변화율 $\frac{\Delta B}{B}$가 수익률 변화분과 반대방향으로 $D$의 비율만큼 움직인다는 것을 의미합니다. 이러한 관점에서 듀레이션을 채권가격의 민감도라고 표현합니다.

DV01이란 수익률이 0.01%(1bp)변화할때 채권가격의 변동분을 말합니다. 즉, $DV01=-0.0001\times B\times D$

### Modified duration

연속복리수익률을 사용하지않고 annual 등 복리수익률을 사용하는 경우, 듀레이션과 채권가격 간의 관계는 다음과 같습니다.

$$\Delta B=-\frac{BD\Delta y}{1+y/m}$$

이러한 이자율 측정방법간 차이를 보정하기 위해 수정듀레이션을 $D^*=\frac{D}{1+y/m}$이라고 하며, $\Delta B=-BD^*\Delta y$를 사용합니다.

### Bond portfolios

채권으로 포트폴리오를 구성할 때, 상기 듀레이션에 관한 식을 모두 적용할 수 있습니다. 다만, 유의해야할 점은 $\Delta y$는 모든 채권수익률이 변화할때를 말한다는 것 입니다. 즉, 채권의 만기에 따른 수익률 곡선이 평행하게 이동(parallel shift)할 때만 듀레이션을 이용한 계산을 적용할 수 있습니다.

금융기관은 부채와 자산간의 듀레이션을 일치시키는 방법으로 금리변화에 따른 위험을 회피할 수 있습니다. 그러나, 금리 곡선이 평행하게 이동하지 않고 가파르거나 평평하게 움직이는 것에 대한 위험은 여전히 남아있습니다.

## 4.11 Convexity

듀레이션을 이용한 채권가격변화분은 수익률 변화분이 커질수록 정밀도가 떨어집니다. 이때 이용하는 것이 Convexity로, non-linear한 채권 가격을 듀레이션을 통해 linear하게 추정할때, 오차분을 보정해주는 역할을 합니다.

$$C=\frac{1}{B}\frac{d^2B}{dy^2}=\frac{\sum c_it_i^2e^{-yt_i}}{B}$$

한편, 테일러 급수를 활용하여 2차 다항함수까지 전개한 채권가격에 듀레이션과 컨벡서티를 적용한 식은 다음과 같습니다.

$$\Delta B=\frac{dB}{dy}\Delta y+\frac{1}{2}\frac{d^2B}{dy^2}\Delta y^2=-BD\Delta y+\frac{1}{2}BC(\Delta y)^2$$
$$\Rightarrow\frac{\Delta B}{B}=-D\Delta y+\frac{1}{2}C(\Delta y)^2$$

포트폴리오의 컨벡서티까지 0에 가깝게하는 경우(감마헷지), 이자율이 크게 변화하더라도 어느정도 보정할 수 있으나, 역시 가파르거나 평평하게 수익률 곡선이 움직이는 경우의 위험은 존재합니다.

## 4.12 Theories of the term structure of interest rates

제로금리 커브는 일반적으로 로그함수처럼 완만하게 우상향하는 곡선이지만, 때때로는 flat하기도, 우하향하기도 하며 심지어는 기간에따라 등락을 반복하기도 합니다. 이를 설명하는 금리의 기간구조에 대해서는 많은 이론들이 존재합니다. 

1. *expectations theory* : 장기금리는 미래의 단기금리의 기대값과 동일. 현재의 선도금리가 미래의 제로금리의 기대값.
2. *market segmentation theory* : 단기, 중기, 장기금리는 각각 시장참여자가 달라 서로 큰 관계가 없으며, 각 시장별 투자자의 수급이나 전망에 따라 형성.
3. *liquidity preference theory* : 유동성 선호이론. 사람들은 현금을 보유하는 것을 선호하므로, 돈을 빌릴때 장기간으로 빌리고 싶어함. 따라서 금리는 일반적으로 우상향. 선도금리가 제로금리보다 높게 형성. 현실과 가장 부합.