# Chapter 17 {.unnumbered}

주가지수옵션 및 통화옵션

*(Options on Stock Indices and Currencies)*

## 17.1 Options on stock indices

주가지수옵션도 매우 활발히 거래되는 옵션입니다.

시장 전체를 대표하는 DJIA, S&P500, Nasdaq100 등에 대한 주가지수옵션이 CBOE에서 활발히 거래되고 있으며, 각 산업섹터별로 존재하는 주가지수에 대한 옵션도 존재합니다.

주가지수옵션은 포트폴리오 보험(보호적 풋), 커버드 콜과 같은 전략적인 투자를 위해 주로 거래됩니다.

보유한 주식 포트폴리오의 베타가 1인 경우, 시장지수에 대한 주가지수옵션을 포트폴리오 보험에 활용할 수 있습니다.

포트폴리오의 가치와 동일한 만큼의 풋옵션을 매수한다면, 풋옵션의 행사가격 미만으로 지수가치가 떨어졌을때에 한하여 손실을 회피(coverage)할 수 있습니다.

베타가 1이 아닌 경우, 포트폴리오 베타를 고려한 가치만큼 풋옵션을 매수함으로써 포트폴리오 보험을 구축할 수 있습니다.

## 17.2 Currency options

통화옵션은 기본적으로 장외에서 활발히 거래되는 옵션입니다.

장외옵션의 특성상 행사가격도 매우 다양하고, 만기일이나 다른 상품 스펙을 계약당사자 간에 자유롭게 정할 수 있는 장점이 있습니다.

Nasdaq OMX 등 거래소에서도 통화옵션이 거래되기는 하지만, 그 규모는 장외시장 대미 매우 작습니다.

통화옵션을 이용한 대표적인 거래전략으로는 Range forwards가 있습니다.

행사가격이 낮은 풋옵션을 매수하고, 행사가격이 높은 콜옵션을 매도하면, 행사가격 사이 구간의 만기 payoff는 flat하고 나머지는 기울기가 -1인 형태가 되는데, 이를 Short range forwards라고 합니다.

Short range forwards와 현물통화를 가지고 있다면, bull call spread와 유사한 만기 payoff를 가지게 됩니다.

## 17.3 Options on stocks paying known dividend yields

지금까지 모든 옵션 프라이싱은 배당이 없는 경우에 한정하였습니다.

그러나 실제 세상의 주식은 대부분 배당이 있습니다.

이제 이러한 배당을 가격결정에 어떻게 적용하는지 살펴보겠습니다.

방법은 간단합니다.

주식의 배당이 연속복리 배당수익률 $q$로 주어져있다고 가정하는 것 입니다.

그렇다면, 주식의 기대수익률이 $k$일 때, 만기 $T$시점까지 주가의 기대값 $E(S_T)=S_0e^{(k-q)T}$가 될 것입니다.

위험중립세상에서는 어떨까요? 동일한 방식을 적용하면 $E(S_T)=S_0e^{(r-q)T}$가 될 것 입니다.

이제, 두가지 포트폴리오를 비교해봅시다.

1. 연속복리 배당수익률 $q$로 주어져있으며, 현재 가격이 $S_0$인 주식
2. 배당이 없으며, 현재 가격이 $S_0e^{-qT}$인 주식

두가지 포트폴리오의 만기 $T$시점의 기대값은 $S_0e^{(k-q)T}$로 동일합니다. 즉, 배당이 있고 현재 가격이 $S_0$인 경우는, 배당이 없으며 현재 가격이 $S_0e^{-qT}$인 경우와 동일합니다.

이 방식으로 전개할 때, 앞서 살펴본 옵션의 가격결정과 관련된 수식에서 $S_0$를 $S_0e^{-qT}$로 치환하면 배당이 있는 경우에 대한 결과를 얻을 수 있습니다.

### Lower bounds for option prices

$$c\geq max(S_0e^{-qT}-Ke^{-rT},0),\;\;p\geq max(Ke^{-rT}-S_0e^{-qT})$$

### Put-call parity

$$c-p=S_0e^{-qT}-Ke^{-rT}$$

$$S_0e^{-qT}-K\leq C-P\leq S_0-Ke^{-rT}$$

### Stochastic process & BSM equition and formulas

$$dS=(r-q)S\,dt+\sigma S\,dz$$

$$\frac{\partial f}{\partial t}+(r-q)S\frac{\partial f}{\partial S}+\frac{1}{2}\sigma^2S^2\frac{\partial^2f}{\partial S^2}=rf$$

$$c=S_0e^{-qT}N(d_1)-Ke^{-rT}N(d_2)\;for\;d_1=\frac{\ln(S_0e^{(r-q+\frac{1}{2}\sigma^2)T})-\ln K}{\sigma\sqrt{T}},\;d_2=d_1-\sigma\sqrt{T}$$

### 17.4 Valuation of european stock index options

주가지수옵션의 가격결정공식은 무위험이자율과 배당수익률이 $r,q$로 주어져있을 때 위에서 살펴본 바와 동일합니다.

여기서는 선물의 이론가격 $F_0=S_0e^{(r-q)T}$를 이용하여 옵션가격을 결정하는 방법을 추가로 살펴보겠습니다.

위 콜옵션의 BSM공식에 선물의 이론가격을 대입하여 정리하면,

$$c=F_0e^{-rT}N(d_1)-Ke^{-rT}N(d_2)\;for\;d_1=\frac{\ln(F_0e^{\frac{1}{2}\sigma^2T})-\ln K}{\sigma\sqrt{T}},\;d_2=d_1-\sigma\sqrt{T}$$

또한, 풋콜패리티는 $c-p=(F_0-K)e^{-rT}$로 정리할 수 있습니다.

이를 이용해 주가 및 배당수익률을 확정하기 어려운 상황에서 선물가격을 이용해 옵션가격을 계산할 수 있습니다.

### 17.5 Valuation of European currency options

앞서 우리는 배당이 있는 주식은, 배당이 없고 현재가격이 $S_0e^{-qT}$인 경우와 동일하다고 가정하고 식을 전개하였습니다.

통화옵션의 경우, 통화선물의 이론가격이 $F_0=S_0e^{(r-r^f)T}$임을 고려해보겠습니다.

만약 국내 무위험이자율이 $r$, 해외 무위험이자율이 $r^f$, 현재 환율이 $S_0$로 주어져 있다고 하면, 이는 국내 무위험이자율이 $r$, 해외 무위험이자율은 $0$, 현재 환율이 $S_0e^{-r^fT}$로 주어져 있는 경우와 동일할 것 입니다.

이를 적용한다면 상기 전개한 배당이 적용된 옵션에 대한 수식에서, $q$를 $r^f$로 치환함으로써 통화옵션의 가격결정공식을 모두 유도할 수 있습니다. 즉, 아래와 같습니다.

$$c=S_0e^{-r^fT}N(d_1)-Ke^{-rT}N(d_2),\;\;c-p=S_0e^{-r^fT}-Ke^{-rT}$$

### 17.6 American Options

미국형 옵션의 경우, Binomial Tree 모형(CRR)을 통해 마지막 노드부터 조기상환 가능성을 고려해가면서 순차적으로 현재가치로 환산한다면 그 가치를 결정할 수 있습니다.

이 때, 위험중립가치평가를 통해 주가의 상승확률 $p=\frac{e^{r\Delta T}-d}{u-d}$를 결정하였습니다.

배당이 있는 경우의 주식옵션, 주가지수옵션 및 통화옵션의 경우 위와 동일한 논리를 적용할 수 있고, 이에 따른 위험중립확률은 아래와 같습니다.

$$p=\frac{e^{(r-q)\Delta T}-d}{u-d}=\frac{e^{(r-r^f)\Delta T}-d}{u-d}\;\;for\;\;u=e^{\sigma\sqrt{\Delta T}},\;d=1/u$$