# Chapter 11 {.unnumbered}

Properties of Stock Options

## 11.1 Factors Affecting Option Prices

옵션 가격에 영향을 미치는 요소는 크게 6가지가 있으며, 이 변수들과 옵션 가격과의 상관관계는 다음과 같습니다.

|Variable|European Call|European Put|American call|American put|
|:-------|:-----------:|:----------:|:-----------:|:----------:|
|Current stock price, $S_0$|+|-|+|-|
|Strike prkce, $K$|-|+|-|+|
|Time to expiration, $T$|?|?|+|+|
|Volatility, $\sigma$|+|+|+|+|
|Risk-free rate, $r_f$|+|-|+|-|
|Amount of future dividend, $d$|-|+|-|+|

1. 주가 및 행사가격 : 만기 pay-off를 고려하면 쉽게 이해할 수 있습니다.
2. 만기
    - 미국형 : 언제나 행사할 수 있으므로 만기가 길수록 옵션 가치는 증가
    - 유럽형 : 일반적으로 만기가 길수록 옵션 가치가 증가하지만, 중도배당이 존재하는 경우나 Deep-ITM 풋옵션의 경우에서는 만기가 짧은 옵션이 유리한 경우도 존재함
3. 변동성 : 간단히 설명하자면, 옵션 매수자의 경우 이익은 제한이 없고 손실은 프리미엄으로 제한되어 있으므로 변동성이 클 수록 옵션 기대이익이 증가하게 되므로 변동성과 옵션가격은 항상 양의 상관관계에 있음
4. 무위험이자율 : 일반적으로 무위험이자율이 증가하면 주가의 요구수익률이 증가하게 되고, 더불어 미래 현금흐름의 현재가치가 감소하는 효과가 있음. 즉, 콜옵션의 가치는 증가하고 풋옵션의 가치는 감소하는 경향이 있음.
5. 배당 : 배당이 존재하면 배당락으로 주가가 하락함. 콜옵션의 가치는 감소하고 풋옵션의 가치는 증가함.

## 11.2 Assumptions and Notation

이전 챕터와 동일하게 모든 시장참가자는 거래비용이 없고, 동일한 세율을 적용받으며, 무위험이자율로 빌리거나 빌려줄 수 있다는 가정을 사용할 것 입니다.

대문자는 American option을, 소문자는 European option을 의미합니다.

## 11.3 Upper and Lower Bounds for Option Prices

### Upper bound

기본적으로, 권리행사를 통해 행사가격을 지불하고 주식을 사거나(콜), 행사가격에 주식을 파는(콜) 옵션의 성질에 따라 콜옵션은 현재 주가보다 비쌀 수 없고, 풋옵션은 행사가격의 현재가치보다 비쌀 수 없습니다.

콜옵션이 현재 주가보다 비싸다면 콜옵션 매도+주식 매수를, 풋옵션이 행사가격의 현재가치보다 비싸다면 풋옵션 매도+무위험이자율에 투자함으로써 간단한 차익거래가 가능하기 때문입니다.

$$C\leq S_0,\;\; c\leq S_0,\;\; P\leq K,\;\; p\leq Ke^{-rT}$$

### Lower bound for Non-dividend

### European

두 가지 포트폴리오를 비교해보겠습니다.

1. 콜옵션 매수($c$) 및 행사가격의 현재가치($Ke^{-rT}$)만큼 무위험이자율에 투자
2. 주식을 현재가격($S_0$)에 매수

만기시점 $T$에 두 포트폴리오의 가치는 다음과 같습니다.

1. $max(S_T-K,0)+K=max(S_T,K)$
2. $S_T$

이에 따라, 포트폴리오 1의 가치는 항상 2보다 커야하므로, $c\geq S_0-Ke{-rT}$가 만족합니다.

마찬가지로,

1. 풋옵션 매수($p$) 및 주식을 현재가격($S_0$)에 매수
2. 행사가격의 현재가치($Ke^{-rT}$)만큼 무위험이자율에 투자

만기시점 $T$에 두 포트폴리오의 가치는 다음과 같습니다.

1. $max(K-S_T,0)+S_T=max(K,S_T)$
2. $K$

이에 따라, $p\geq Ke{-rT}-S_0$가 만족합니다.

한편, 옵션의 가치는 항상 0보다 크거나 같아야하므로 배당이 없는 유럽형 옵션의 하한은 다음과 같습니다.

$$c\geq max(S_0-Ke{-rT},0),\;p\geq max(Ke^{-rT}-S_0,0)$$

### American

먼저, 배당이 없을 때는 콜옵션의 시간가치가 항상 0보다 크거나 같으므로 미국형 콜옵션과 유럽형 콜옵션의 가격이 항상 같습니다.

::: {.callout-tip}
배당이 없다면, 조기행사의 가치는 "0"입니다.

만약, 만기 이전에 내재가치가 높아 미국형 콜옵션을 조기행사하고자 하는 투자자가 있다면, 조기행사 대신에 주식을 공매도하고 공매도대금을 무위험이자율에 투자함으로써 무위험차익을 얻을 수 있습니다.

직관적으로, 주식을 보유함으로써 발생하는 (+) 현금흐름이 없으므로, 미리 주식을 매수함으로써 얻는 이익은 없지만 행사가격만큼의 현금에 대한 기회비용이 발생하기 때문에 조기행사의 가치가 0이됩니다.

반면, 풋옵션의 경우 조기행사함으로써 행사가격만큼 현금이 들어오기 때문에 조기행사할 유인이 발생할 수 있습니다.
:::

한편, 미국형 풋옵션은 언제나 권리행사를 할 수 있으므로 $P\geq max(K-S_0,0)$의 하한을 갖게 됩니다.

옵션의 종류별로 상한 및 하한을 정리하면 아래와 같습니다.

$$max(S_0-Ke^{-rT})\leq c=C\leq S_0$$

$$max(Ke^{-rT}-S_0)\leq p\leq Ke^{-rT},\;\;max(K-S_0,0)\leq P \leq K$$

## 11.4~6 Put-Call Parity

옵션 하한을 산출할 때 이용한 포트폴리오를 이용해 콜옵션과 풋옵션의 가격간에 중요한 관계를 유도할 수 있습니다.

콜옵션과 풋옵션의 포트폴리오 1을 주목해봅시다.

1. 콜옵션 매수($c$) 및 행사가격의 현재가치($Ke^{-rT}$)만큼 무위험이자율에 투자
2. 풋옵션 매수($p$) 및 주식을 현재가격($S_0$)에 매수

만기시점의 포트폴리오의 가치는 다음과 같습니다.

1. $max(S_T-K,0)+K=max(S_T,K)$
2. $max(K-S_T,0)+S_T=max(K,S_T)$

즉, 두 포트폴리오는 만기 $T$ 시점에 동일한 Pay-off를 가지고 있는 동일한 포트폴리오입니다.

따라서 두 포트폴리오의 가치는 동일해야하므로, 아래와 같이 Put-Call parity를 유도할 수 있습니다.

$$c+Ke^{-rT}=p+S_0$$

::: {.callout-tip title="ATM 옵션의 가격"}
Put-call parity에서 ATM($S_0=K$) 옵션인 경우,

$$c+S_0e^{-rT}=p+S_0\Rightarrow c-p=S_0(1-e^{-rT})>0$$

즉, ATM에서는 콜옵션의 가치가 풋옵션보다 높은 것을 알 수 있습니다.
:::

### Parity in American options{#sec-AmericanParity}

풋콜패리티는 유럽형 옵션에서만 성립하므로, 미국형 옵션에서는 이와 유사한 부등식을 유도할 수 있습니다.

먼저, 다음 세가지 포트폴리오를 고려해보겠습니다.

1. 콜옵션 매수($c$) 및 행사가격의 현재가치($Ke^{-rT}$)만큼 무위험이자율에 투자
2. 풋옵션 매수($p$) 및 주식을 현재가격($S_0$)에 매수
3. 미국형 풋옵션 매수($P$) 및 주식을 현재가격($S_0$)에 매수

Put-call parity에 따라 1과 2의 가치가 같고, 미국형 옵션의 가치는 유럽형 옵션보다 항상 크거나 같으며, 배당이 없을 때는 미국형 콜옵션과 유럽형 콜옵션의 가격이 같으므로 아래와 같이 정리할 수 있습니다.

$$c+Ke^{-rT}=p+S_0\leq P+S_0\Rightarrow c-P=C-P\leq S_0-Ke^{-rT}$$

다음으로, 두가지 포트폴리오를 고려해보겠습니다.

1. 유럽형 콜옵션 매수($C$) 및 행사가격($K$)만큼 현금 보유
2. 미국형 풋옵션 매수($P$) 및 주식을 현재가격($S_0$)에 매수

먼저, 조기행사 없이 만기보유하는 경우 두 포트폴리오의 가치는,

1. $max(S_T-K,0)+Ke^{rT}=max(S_T,K)+K(e^{rT}-1)$
2. $max(K-S_T,0)+S_T=max(K,S_T)$

포트폴리오 1에서는 현금에서 무위험이자율만큼 수익이 발생하므로 포트폴리오 2보다 가치가 높게 됩니다.

다음으로, 풋옵션에서 조기행사가 발생하는 경우를 살펴보겠습니다. 

조기행사가 $0<t<T$ 인 t시점에 발생한다면, $t$시점에 풋옵션의 포트폴리오 2의 가치는 $K$가 되며 만기 $T$ 시점에는 $Ke^{r(T-t)}$가 됩니다.

반면, $T$ 시점에 포트폴리오 1의 가치는 옵션이 없더라도 $Ke^{rT}$이므로, 항상 포트폴리오 1의 가치가 크거나 같게됩니다.

즉, $C+K=c+K\geq P+S_0$가 만족하며, 상한 및 하한을 정리하면 아래와 같습니다.

$$S_0-K\leq C-P\leq S_0-Ke^{-rT}$$

## Effect of Dividends

### European

이제, 배당이 있는 경우를 살펴보겠습니다. 만기시점까지 주식에서 발생하는 배당금의 현재가치를 $D$라고 하고, 다음 포트폴리오를 살펴보겠습니다.

1. 유럽형 콜옵션 매수($c$) 및 $D+Ke^{-rT}$만큼 무위험이자율에 투자
2. 주식 매수($S_0$)
3. 유럽형 풋옵션 매수($p$) 및 주식 매수($S_0$)
4. $D+Ke^{-rT}$만큼 무위험이자율에 투자

위와 같은 방식으로 만기 $T$시점에 각 포트폴리오의 가치를 비교하면,

1. $max(S_T-K,0)+De^{rT}+K=max(S_T,K)+De^{rT}$
2. $S_T+De^{rT}$
3. $max(K-S_T,0)+S_t+De^{rT}=max(K,S_T)+De^{rT}$
4. $De^{rT}+K$

각 옵션의 하한 및 풋콜패리티를 정리하면,

$$(1)\geq (2)\Rightarrow c\geq max(S_0-D-Ke^{-rT},0)=max(S_0e^{-dT}-Ke^{-rT})$$

$$(3)\geq (4)\Rightarrow p\geq max(D+Ke^{-rT}-S_0,0)=max(Ke^{-rT}-S_0e^{-dT})$$

$$(3)\equiv(4)\Rightarrow c+D+Ke^{-rT}=p+S_0\Rightarrow c-p=S_0-D-Ke^{-rT}=S_0e^{-dT}-Ke^{-rT}$$

::: {.callout-tip}
주식의 배당이 기간 중 연속복리배당수익률 $d$로 주어져 있다면, 포트폴리오에서 주식을 매수할 때 $S_0e^{-dT}$만큼 매입하고, 배당은 주식에 재투자한다고 가정하면 등식의 마지막 결과를 얻을 수 있습니다.
:::

### American

앞서 배당이 없는 경우에서 $C-P\leq S_0-Ke^{-rT}$가 성립하는 것을 살펴보았습니다.

변수와 옵션가격 간의 관계에서, 배당은 콜옵션에서 (-), 풋옵션에서 (+)인 것을 확인하였습니다. 나중에 살펴보겠으나, 동일한 배당이 존재한다면 이 둘의 변화는 상쇄될 수 있습니다.

따라서 $C-P$ 포트폴리오에서 배당이 존재하는 경우, 두 변화분은 상쇄되므로 변동이 없게 되고, 따라서 배당이 존재하는 경우에 대해서도 위의 상한이 성립하게 됩니다.

다음으로, 두가지 포트폴리오를 고려해보겠습니다.

1. 유럽형 콜옵션 매수($c$) 및 $D+K$를 무위험이자율에 투자
2. 미국형 풋옵션 매수($P$) 및 주식 매수($S_0$)

조기행사가 없다면 만기 $T$시점의 가치는 포트폴리오 1이 항상 크거나 같습니다.

1. $max(S_T-K,0)+(D+K)e^{rT}=max(S_T,K)+De^{rT}+K(e^{rT}-1)$
2. $max(K-S_T)+S_T+De^{rT}=max(K,S_T)+De^{rT}$

다음으로, 배당이 발생한 후 조기행사가 $0<t<T$ 인 t시점에 존재하는 경우, t시점의 포트폴리오 2의 가치는 $K+De^{rt}$이며, 만기 $T$시점의 가치는 $Ke^{r(T-t)}+De^{rT}$입니다.

반면, 포트폴리오 1은 옵션이 없더라도 만기 $T$ 시점에 $(K+D)e^{rT}$만큼의 가치가 있으므로 포트폴리오 1의 가치가 항상 크게 됩니다.

따라서, $C+D+K\geq c+D+K\geq P+S_0$가 성립하며, 미국형 옵션에서 배당을 반영한 부등식은 아래와 같습니다.

$$S_0e^{-dT}-K=S_0-D-K\leq C-P \leq S_0-Ke^{-rT}$$