# Chapter 26 {.unnumbered}

이색옵션 *(Exotic Options)*

지금까지 다루어왔던 유럽형/미국형 콜/풋옵션은 일반적인 종류의 옵션입니다.

이들 옵션을 가장 기초적인 구조라는 의미에서 Plain Vanilla라고 부릅니다.

또한, 이러한 Plain Vanilla 상품들의 집합, 현금/현물/선물/옵션들을 우리는 패키지(Packages)라고 부릅니다.

우리는 지금까지 패키지를 이용해서 여러 포트폴리오를 구성하고, Pricing에 활용하고, 여러 거래전략들을 살펴보았습니다.

그러나 세상에는 이러한 일반적인 종류의 상품 외에도 다양한 현금흐름을 발생시키는 파생상품이 존재합니다.

장외에서 다양한 니즈를 가진 거래자에 의해서 만들어지기 때문입니다.

이런 종류의 옵션을 우리는 이색옵션(Exotic Options)라고 합니다.

## 26.2 Perpetual American call and put options

영구적 미국형 옵션이란, 언제든지 권리행사가 가능한 옵션이며 만기가 없는 옵션입니다.

즉, 옵션의 권리가 권리행사를 할 때 까지 영구적으로 지속된다는 말입니다.

이러한 옵션의 가치평가를 위해서는 언제가 권리행사의 최적시점인지 알아야하고, 이는 최적주가를 $H$라고 하였을 때,

$f=(H-K)(\frac{S}{H})^\alpha$의 pay-off에 대한 미분방정식을 풀어서 해결할 수 있습니다.

## 26.3 Nonstandard American Options

비표준 미국형 옵션이란, 미국형 옵션의 기본적인 틀을 따르면서 Plain Vanilla와는 다른 옵션을 말합니다.

조기행사가 가능하지만 그 시점이 일정시점 이후로 제한되어있는 경우, 이러한 옵션을 버뮤다 옵션이라 부릅니다.

반면, 조기행사가 일정시점까지만 가능한 경우도 있으며, 행사가격이 만기 이전까지 정해진 규칙에 따라 변하는 옵션도 존재합니다.

## 26.4 Gap Options

갭옵션이란 옵션에서 행사가격이 두 종류로 나누어진 종류의 옵션을 말합니다.

예를 들어, 행사가격이 $K_1,K_2$ 두 개로 나누어져 있으며, 하나는 권리행사요건을 결정하고 하나는 권리행사할 때 구매/판매가격을 결정합니다.

예를 들어, 갭콜옵션의 경우 $S_T>K_2$일 때 권리행사가 가능하며 그 때의 pay-off는 $S_T-K_1$입니다.

이러한 콜옵션의 BSM 공식은 아래와 같습니다.

$$c=S_0e^{-qT}N(d_1)-K_1e^{-rT}N(d_2)\;for\;d_1=\frac{\ln{S_0/K_2}+(r-q+\sigma^2/2)T}{\sigma\sqrt{T}},\;d_2=d_1-\sigma\sqrt{T}$$

## 26.5 Forward start options

Forward start options란 미래 특정시점부터 유효한 옵션입니다.

종종 스톡옵션이 이러한 형태를 따르게 됩니다.

대게 미래 특정시점에 옵션이 주어지며, 행사가격은 그 시점의 주가와 동일하게 설정됩니다.

배당이 없는 주식에 대한 Forward start options의 경우, 그 가치는 동일한 만기의 ATM Plain Vanilla 옵션과 동일하게 됩니다.

일반적으로, 현재시점에서 Forward start options의 가치는 $c_{fs}=e^{-rT}\hat{E}[c\frac{S_1}{S_0}]$입니다.

## 26.6 Cliquet Options

클리켓옵션이란 옵션의 만기까지 여러번에 나누어 일정한 규칙으로 행사가격을 재설정하는 옵션입니다.

행사가격이 재설정될때마다 옵션의 내재가치를 지급하게 됩니다.

따라서, 이러한 옵션은 행사가격을 재설정할 때마다의 만기를 가진 여러개의 Forward start options의 합계로 볼 수 있습니다.

## 26.7 Compound Options

복합옵션이란 옵션에 대한 옵션(Options on options)를 말합니다.

기초자산이 콜옵션인 콜/풋옵션, 기초자산이 풋옵션인 콜/풋옵션이 존재하며 그러한 옵션의 가치평가는 두개의 옵션이 중첩된 형태를 확률과정으로 모델링함으로써 계산해볼 수 있습니다.

즉, 옵션 및 기초자산인 옵션에 대한 권리행사를 두번 고려해야하며 이를 위해 이변량 정규분포(Bivariate Normal)를 활용해야 합니다.

## 26.8 Chooser Options

선택옵션이란, 옵션을 가진 사람이 특정시점후에 이 옵션을 콜옵션으로 할지 풋옵션으로 할지 정할 수 있는 옵션입니다.

즉, 그 시점을 T라고 하면 선택옵션의 가치는 $max(c_T,p_T)$가 될 것입니다.

선택옵션의 구조를 살펴보면 스트래들전략(동일한 행사가격의 콜/풋 매수)와 유사한 것을 볼 수 있는데요,

차이점은 선택옵션은 T시점에 옵션종류를 선택하고나면 옵션 만기인 $T_2$까지는 콜 또는 풋옵션으로 Pay-off가 바뀐다는 것 입니다.

스트래들은 만기 $T_2$시점까지 콜/풋 매수를 유지하게 되는 반면, 선택옵션은 만기 $T_2$의 콜 또는 풋을 매수하고 만기 $T$인 나머지 종류의 옵션을 매수하는 형태를 생각하면 됩니다.

## 26.9 Barrier Options

배리어옵션이란 기존 Plain Vanilla 옵션에 권리행사에 대한 배리어가 있는 옵션을 말합니다.

배리어란, Knock-in 또는 Knock-out을 말하며 각각 기초자산의 가격이 특정 가격 이상일때부터 권리행사가 가능하거나 기초자산의 가격이 특정 가격 이상부터는 권리행사가 불가능한 형태입니다.

예를 들어, *up-and-out call*옵션은 기초자산의 가격이 특정 가격 $H$일 때 까지만 권리행사가 가능하며 그 이상에서는 불가능한 옵션입니다.

반대로 *up-and-in call*옵션은 기초자산의 가격이 $H$ 이상일 때만 권리행새가 가능한 옵션입니다.

두 옵션과 기존 옵션의 관계는 $c_{uo}+c_{ui}=c$로 표현할 수 있습니다.

## 26.10 Binary Options

이항옵션이란, 만기의 기초자산의 가격이 특정가격 이상이거나 이하면 Pay-off가 발생하고 조건을 만족하지 않으면 Pay-off가 0인 옵션입니다.

조건을 만족하였을 때 일정현금을 지급하는 Cash-or-Nothing 옵션과 자산을 지급하는 Asset-or-Nothing 옵션으로 나눌 수 있습니다.

### Cash-or-Nothing

만기는 T이며, 기초자산의 가격이 행사가격 K 이상이면 현금 Q를 지급하는 옵션을 Cash-or-Nothing 콜옵션이라고 부릅니다.

반대로, 기초자산의 가격이 행사가격 K 이하이면 현금 Q를 지급하는 옵션을 Cash-or-Nothing 풋옵션이라고 부릅니다.

Pay-off는 간단합니다.

콜옵션의 경우 $S_T>K$이면 $Q$, 아니면 0이 됩니다.

BSM 모형의 $P(S_T>K)=N(d_2)$인 점을 활용하면, Cash-or-Nothing Call의 가격은 $e^{-rT}\;Q\;N(d_2)$가 됩니다.

풋옵션은 $e^{-rT}\;Q\;N(-d_2)$가 되며, 동일한 행사가격의 콜/풋을 매수하면 만기 pay-off는 Q가 되므로 $c+p=e^{-rT}Q$라는 관계가 성립하게 됩니다.

### Asset-or-Nothing

만기는 T이며, 기초자산의 가격이 행사가격 K 이상이면 기초자산 S_T를 지급하는 옵션을 Asset-or-Nothing 콜옵션이라고 부릅니다.

Pay-off는 $S_T>K$이면 $S_T$, 아니면 0이 됩니다.

이 역시 동일한 방법으로 Asset-or-Nothing Call의 가격을 계산해보면 $S_0N(d_1)$이 됩니다.

무엇인가 눈치채셨나요?

European Call 옵션은 Asset-or-Nothing 콜옵션을 매수하고 Cash-or-Nothing 콜옵션을 매도한 것과 같게 됩니다.

### Greeks

먼저, Asset-or-Nothing은 Plain Vanilla 옵션의 구성요소로서 그릭스나 행태가 기존 옵션과 거의 동일합니다.

그러나, Cash-or-Nothing은 Plain Vanilla 옵션의 구성요소이나 그릭스는 매우 다릅니다.

왜 그럴까요?

그 차이는 Cash-or-Nothing 옵션은 최대 이익폭이 정해져있기때문입니다.

기존 옵션은 손실폭이 프리미엄으로 제한되어있고, 이익폭은 정해져있지 않았습니다.

그러나 Cash-or-Nothing 옵션은 최대 이익이 Q로 정해져있기 때문에, 이러한 차이가 발생하게 됩니다.

#### Delta

기초자산의 가격변화에 따른 Cash-or-Nothing Call 옵션의 가격변화는 어떻게 될까요?

당연히 델타는 양수가 될 것 입니다.

그러나, ITM에서 주가의 수준에 관계없이 기대이익은 Q이므로, 델타가 1에 근접했던 기존 옵션과 달리 0으로 수렴하게 됩니다.

ATM에서는 어떻게 될까요?

주가가 행사가격을 기점으로 이익이 0에서 Q로 단층이 발생합니다.

따라서 델타는 ATM에서 가장 크게 되고, 뾰족한 첨점을 가진 형태가 될 것 입니다.

#### Gamma

위의 델타의 형태를 상상해봅시다.

아마도 Bell-shaped graph가 나올 것이며, ATM에서 뾰족한 구조가 됩니다.

따라서 감마는 ATM을 기준으로 양수에서 음수로 전환되며, 0에서는 정의되지 않게 됩니다.

#### Theta

만기가 가까워질수록 옵션의 시간가치는 감소하므로 Plain Vanilla에서 옵션의 Theta는 항상 음수였습니다.

그러나, Cash-or-Nothing의 경우, ITM에서 주가상승에 따른 이익증가는 없는 반면 주가하락에 따라 이익이 Q -> 0이 될 가능성이 존재합니다.

따라서 ITM에서 음의 시간가치를 가지게 되며, 반대로 OTM에서 양의 시간가치를 가지게 됩니다.

따라서 Theta는 음수에서 ATM을 기점으로 양수로 전환되는 형태가 됩니다.

#### Vega

변동성도 비슷한 논리로 설명 가능합니다.

ITM옵션에서 변동성이 커지면 주가하락에 따른 이익이 Q -> 0이 될 가능성이 커집니다.

따라서 Vega는 ITM에서 음수, OTM에서 양수가 됩니다.

## 26.11 Lookback Options

룩백옵션은 만기시점의 기초자산의 가격과 만기시점까지의 가격을 비교해서 pay-off가 정해지는 옵션입니다.

Floating lookback call options란, 만기시점의 기초자산의 가격과 만기시점까지의 기초자산의 최저가격의 차이를 Pay-off로 가지게 됩니다. ($K=S_{min}$)

반면, floating lookback put options는 만기까지의 기초자산의 최대가격과 만기가격의 차이를 지급하는 옵션입니다. ($K=S_{max}$)

Fixed lookback call options는 반대로 만기까지의 최대가격과 행사가격의 차이를 지급합니다. ($S_T=S_{max}$)

Fixed lookback put options는 행사가격과 만기까지의 최저가격의 차이를 지급합니다. ($S_T=S_{min}$)

## 26.12 Shout Options

샤우트 옵션이란, 만기까지 옵션보유자가 "한번" 옵션의 내재가치만큼의 최저이익을 보장받는 구조입니다.

샤우트 시점을 $\tau$라고 하면, 옵션보유자는 $S_\tau-K$만큼의 최저이익을 만기시점에 보장받게 되며, 만약 만기시점의 내재가치가 더 높다면 최저이익 대신 권리행사를 통해 보다 높은 이익을 얻게 됩니다.

즉, 콜옵션보유자가 $\tau$시점에 "shout"한다면, 옵션의 만기 pay-off는 $Max(S_\tau-K,0)+S_\tau-K$가 됩니다.

## 26.13 Asian Options

아시안 옵션이란 옵션의 내재가치가 그 시점의 기초자산가격이 아닌 평균가격을 사용하는 옵션입니다.

즉, $S_T\rightarrow S_{avg}$를 사용하게 됩니다.

아시안옵션에서 $S_{avg}$를 log-normal로 가정하면 가치평가는 BSM에 따라 간단히 정리할 수 있지만,

실제로 log-normal의 산술평균은 log-normal을 따르지 않으므로 아시안옵션의 가치평가는 매우 어려운 과제입니다.

## 26.14 Exchange Options

교환옵션이란, 하나의 자산을 다른 하나와 교환할 권리를 가진 옵션입니다.

하나의 통화를 다른 통화와 교환하게되는 통화옵션은, 구조적으로 교환옵션의 일종입니다.

교환옵션의 만기 Pay-off를 일반화하면 $max(V_T-U_T)$가 됩니다.

## 26.15 Options involving several assets

두개 이상의 위험자산을 포함하는 옵션을 무지개옵션(rainbow options)라고 합니다.

CBOT의 실물인수도 채권옵션이 여기에 해당합니다.

옵션 매도자가 인도할 수 있는 종류의 채권이 매우 다양하고, 매도자가 그 중에서 선택하기 때문입니다.

가장 유명한 무지개옵션으로는 기초자산을 특정 주식집단으로 하는 바스켓옵션(Basket option)이 있습니다.

## 26.16 Volatility and Variance Swaps

변동성 및 분산스왑은 어떠한 기초자산에 대하여 특정 기간동안 실현된 변동성 및 분산과 사전에 정해둔 fixed 변동성 및 분산을 교환하는 스왑계약입니다.

변동성은 기간중 기초자산의 일별 로그수익률의 표본표준편차를 연환산해서 산출하게 됩니다.

$$\bar{V}=\bar{\sigma}^2=252\times\frac{\sum_{i=1}^{n-1}[\ln(\frac{S_{i+1}}{S_i})]^2}{n-2}$$

즉, 변동성 및 분산스왑의 만기 Pay-off는 아래와 같습니다.

$$L_{vol}(\bar{\sigma}-\sigma_K),\;\;L_{var}(\bar{V}-V_K)=L_{var}(\bar{\sigma}^2-\sigma_K^2)$$

보통 $L_{var}=L_{vol}/(2\sigma_K)$로 치환하여 많이 쓰입니다.

실무적으로 변동성스왑보다는 분산스왑이 많이 쓰이곤 합니다.

이는 분산스왑의 경우, 콜/풋옵션의 조합으로 만기 pay-off를 복제할 수 있어 가치평가가 보다 쉽기 때문입니다.

분산스왑을 활용하여 S&P500지수의 내재변동성을 지수화한 VIX지수가 매우 유명한데요, 다른 말로 공포지수라고도 불립니다.

## 26.17 Static Options Replication

Binary options 등 일부 이색옵션은 plain vanilla 옵션을 이용해서 pay-off를 복제할 수 있습니다.

그러나 대부분의 이색옵션은 그렇지 않은데, 이 경우 가치평가는 매우 어려운 과제가 됩니다.

이 때 사용할 수 있는 방법 중 하나가 Static Options Replication입니다.

이는 이색옵션의 일정 범위에 한하여 pay-off가 동일한 포트폴리오를 구성하는 것 입니다.

복제 포트폴리오는 이색옵션 전체는 아니지만 일정 범위에 한하여 동일한 pay-off를 가지게 되고,

순간적인 변화에 대해서 이색옵션을 Hedge할 수 있게 됩니다.