# Chapter 18 {.unnumbered}

선물옵션 및 블랙모형

*(Futures Options and Black's Model)*

지금까지 다룬 옵션은 주로 특정 현물을 기초자산으로 하는 옵션이였습니다.

기초자산이 만약 선물이면 어떨까요? "선물계약"을 사거나 파는 권리인데, 이를 선물옵션이라고 부릅니다.

이번 장에서는 선물옵션의 특징과 현물옵션과의 관계, Futures-style options가 무엇인지 알아보겠습니다.

## 18.1 Nature of Futures Options

선물옵션은 옵션이기때문에 의무가 아닌 "권리"입니다.

선물 콜옵션이란, 가격과 만기가 정해진 "선물"을 "매수"할 권리이며, 선물 풋옵션이란 "선물"을 "매도"할 권리입니다.

만기 Pay-off는 기초자산의 가격 $S$ 대신 선물가격 $F$를 생각하면 됩니다.

선물콜옵션 : $max(F-K,0)$ 및 선물풋옵션 : $max(K-F,0)$

선물옵션을 거래할 때에는 "옵션"의 만기일과 기초자산인 "선물"의 만기일이 각각 존재함에 유의해야합니다.

일반적으로 선물옵션은 American Options이며, 옵션의 만기는 선물의 만기일보다 짧은 경우가 대부분입니다.

::: {.callout-note title="18.2 Reasons for the popularity of futures options"}
현물에 대한 옵션 대신 선물에 대한 옵션을 거래하는 근본적인 이유는 무엇일까요?

당연하게도 선물옵션이 현물옵션 대비 장점이 있기 때문인데, 바로 "편리함"입니다.

대게 선물은 현물 대비 거래소에서 즉시 거래할 수 있으며, 유동성이 높은 경우가 많습니다.

또한, 선물은 만기일 이전에 거래소에서 반대거래로 포지션을 해소하거나 현금결제 방식으로 최종결제할 수 있어 현물을 인수도받지 않고 거래를 종결할 수 있습니다.

마지막으로, 이러한 편리함으로 인해 선물의 거래비용이 대게 현물의 거래비용보다 저렴합니다.
:::

## 18.3~5 Pay-off, Put-call parity, Bounds for Futures Options

### Pay-off

선물 콜옵션의 만기 pay-off는 $max(F_T-K,0)$ 입니다.

일반적인 옵션에서 만기시점의 기초자산의 가격 $S_T$가 $F_T$로 바뀐 구조인데요, 만약 선물옵션의 만기가 기초선물의 만기와 동일하다면 $F_T=S_T$이므로, 선물옵션의 만기 pay-off는 일반 옵션과 동일하게 됩니다.

### Put-call parity

풋콜패리티의 경우, 현물 대신 선물가격을 단순 치환할 수 없습니다.

이는 선물에는 현물과 달리 보유에 대한 기회비용인 무위험이자율이 적용되지 않기 때문입니다.

따라서, 옵션의 만기와 선물의 만기가 동일한 선물옵션의 풋콜패리티는 일반적인 경우와 동일하게 됩니다.

$$c-p=S_0-Ke^{-rT}=F_0e^{-rT}-Ke^{-rT}$$

::: {.callout-note title="Building portfolio"}
Portfolio A : a European call futures option + cash $Ke{-rT}$

Portfolio B: a European put futures option + long futures + cash $F_0e^{-rT}$

두 포트폴리오의 만기 Pay-off를 비교해보면 풋콜패리티를 유도할 수 있습니다.
:::

### Bounds

풋콜패리티를 이용하여 선물옵션의 하한을 다음과 같이 유도할 수 있습니다.

$$c\geq c-p=(F_0-K)e^{-rT}\Rightarrow c\geq max((F_0-K)e^{-rT},0)$$

$$p\geq p-c=(K-F_0)e^{-rT}\Rightarrow p\geq max((K-F_0ß)e^{-rT},0)$$

미국형 선물옵션은 언제든지 권리행사가 가능하므로, 내치가치가 하한이 됩니다.

$$C\geq max(F_0-K,0),\;\;P\geq max(K-F_0,0)$$

## 18.6~9 Valuation of a futures options

현물과 달리 선물을 보유하는데에는 초기비용이 들지 않습니다.

즉, 현물을 매수하는 것에 대한 기회비용인 무위험이자율 r이 발생하지 않는다는 의미입니다.

이를 이용하여 위에서 풋콜패리티를 유도하였고, 앞서 살펴보았던 위험중립가치평가, 이항모형, 블랙숄즈모형을 모두 유도할 수 있습니다.

### 위험중립가치평가

위험중립세계를 가정해봅시다. 여기서는 모든 자산의 기대수익률이 무위험이자율 $r$입니다.

선물은 어떨까요? 선물은 계약시점에 현금을 지불하지 않고 만기시점에 지불합니다.

두가지 포트폴리오를 생각해봅시다.

1. 현물 매수
2. 현물 매수 + 선물 매도

두 포트폴리오는 위험중립세계에서는 동일한 기대수익률 $r$을 가지게됩니다.

다시 말해, 위험중립세계에서 선물의 기대수익률은 "0"입니다.

### 이항모형

위험중립세계에서 선물의 기대수익률은 0이므로, 위험중립확률은 $p=\frac{1-d}{u-d}$입니다.

### 블랙숄즈모형

위험중립세계에서 선물의 기대수익률은 0이므로, 선물은 drift rate가 0인 $dF=\sigma F\,dz$ 이토과정을 따르게 됩니다.

앞서 블랙숄즈미분방정식에 $r=0$을 적용하면, 선물옵션에 대한 미분방정식을 얻을 수 있습니다.

$$rf\;=\;\frac{\partial f}{\partial t}\;+\;rS\frac{\partial f}{\partial S}\;+\;\frac{1}{2}\frac{\partial^2f}{\partial S^2}\sigma^2S^2\;=\;\frac{\partial f}{\partial t}\;+\;\frac{1}{2}\frac{\partial^2f}{\partial S^2}\sigma^2S^2$$

동일한 방식으로 선물옵션의 블랙숄즈공식을 유도할 수 있습니다.

$$c\;=\;e^{-rT}\,(F_0\,N(d_1)\;-\;K\,N(d_2))$$

$$p\;=\;e^{-rT}\,(K\,N(-d_2)\;-\;F_0\,N(-d_1))$$

$$where\;d_1=\frac{\ln(F_0/K)+\sigma^2T/2}{\sigma\sqrt{T}},\;\;d_2=d_1-\sigma\sqrt{T}$$

## 18.9 American vs. European for futures options

지금까지 선물은 현물과 달리 기회비용이 없다는 것을 이용하여 풋콜패리티 및 가치평가를 전개하였습니다.

우리는 앞서 배당이 없는 주식의 경우, 콜옵션이 조기행사될 가치가 없으므로 미국형 콜옵션의 가치는 유럽형 콜옵션과 같다는 것을 확인하였습니다.

바로 미국형 콜옵션이 조기행사되더라도, 현물을 매수하는 비용 $S_t$에 대한 만기까지의 기회비용 $S_te^{r(T-t)}$가 발생하기 때문입니다.

선물옵션에서는 어떨까요?

선물은 기회비용이 없으므로 상기 논리를 적용할 수 없습니다. 따라서 배당이 없는 주식에 대한 선물 콜옵션은 조기행사될 수 있으며, 미국형 선물 콜옵션이 유럽형 선물 콜옵션보다 비싸게 될 것 입니다.

현물옵션과 비교하면 어떨까요?

이는 시장 상황이 contango($F>S$)인지 Backwardation($S>F$)인지에 따라 달라집니다.

현재 시장이 contango인 경우, 선물 가격이 현물 가격보다 높습니다. 이 경우 동일한 행사가격을 가지는 선물옵션과 현물옵션을 비교해보면, 콜옵션은 선물옵션이 더 비싸고 풋옵션은 현물옵션이 더 비싸게 형성됩니다.

반대로 Backwardation의 경우, 콜옵션은 현물옵션이 더 비싸고 풋옵션은 선물옵션이 더 비싸게 됩니다.

## 18.10 Futures-style options

선물식 옵션(futures style options)이란, 선물처럼 거래하는 옵션을 말합니다. 일반적으로 프리미엄을 주고받고 만기에 권리행사 유무에 따라 최종결제하는 옵션과 달리, 선물처럼 증거금만을 납입하고 옵션프리미엄의 변동에 따라 일일정산을 수행하는 옵션입니다.

따라서, 옵션의 가격변동에 배팅하는 파생상품이라고 할 수 있으며, 옵션을 기초자산으로 하는 선물이라고 할 수 있습니다.

선물의 이론가격이 미래가치인 $F_0=S_0e^{rT}$로 결정되는 점을 고려하여 선물식 옵션의 미래가치를 각각 유도할 수 있습니다.

$$Futures\;style\;options,\;F^c_0=ce^{rT}=F_0\,N(d_1)\;-\;K\,N(d_2)$$

$$F^p_0=pe^{rT}=K\,N(-d_2)\;-\;F_0\,N(-d_1)$$

이러한 미래가치를 이용하여 선물식옵션의 풋콜패리티를 최종적으로 산출할 수 있으며, 아래와 같습니다.

$$c-p=F_0-K$$