# Chapter 15 {.unnumbered}

블랙-숄즈-머튼 모형

*(The Black-Scholes-Merton Model)*

1970년대 처음 소개되면서 금융시장에 큰 변화를 이끌었고, 그 공로를 인정받아 97년 노벨상까지 수상한 블랙-숄즈-머튼 모형입니다.

이 책에서는 머튼의 방식으로 공식을 유도할 것이며, 배당이 없는 유럽형 콜옵션에서부터 풋옵션, 배당이 있는 경우, 아메리칸 옵션까지 확장해나가는 방법도 소개할 예정입니다.

## 15.1~3 Lognormal Property & Expected return

블랙-숄즈-머튼 모형에서 사용하는 주가모형은 앞 장에서 살펴본 내용과 동일합니다.

즉, 매우 작은 시간 $\Delta t$에 대해 주가수익률은 정규분포를 따르며, 평균은 $\mu$, 표준편차는 $\sigma$ 입니다.

이는 앞서 전개한 바와 같이 주가수익률이 Generalized Wiener Process를 따른다는 의미이며, 주가는 Ito Process를 따르게 됩니다.

주가에 로그를 취한 뒤 Ito's lemma를 적용하면 다시 Generalized Wiener Process를 따르게 되며, 표현하면 아래와 같습니다.

$$\frac{dS}{S}=\mu\;dt+\sigma\;dz\;\Rightarrow\;\ln{S}=(\mu-\frac{\sigma^2}{2})dt+\sigma\;dz$$

$$\Rightarrow\;\ln{S_T}\sim\phi[\ln{S_0}+(\mu-\frac{\sigma^2}{2})T,\;\sigma^2T]$$

주가에 자연로그를 취한 형태가 정규분포를 따른다는 의미를 자세히 살펴보겠습니다.

주가에 적용되는 연속복리수익률 $x$를 가정해보겠습니다.

그러면, $T$시점의 주가 $S_T=S_0e^{xT}$로 표현할 수 있습니다.

이를 $x$에 대해 정리하면 $x=\frac{1}{T}\ln{\frac{S_T}{S_0}}~\phi(\mu-\frac{\sigma^2}{2},\;\sigma^2)$입니다.

즉, 주가의 자연로그를 취한 형태가 정규분포를 따른다면 주가의 연속복리수익률도 유사한 정규분포를 따르게 됩니다.

::: {.callout-note titme="Arithmetic vs. Geometric mean"}
위에서 우리는 주가의 평균변화율이 주가의 기대수익률 $\mu$로 주어져 있을 때, 주가의 연속복리수익률은 평균이 $\mu-\frac{\sigma^2}{2}$인 정규분포를 따른다는 결과를 얻었습니다. 이는 주가의 기대수익률보다 낮은 값입니다.

현재까지 우리는 일반적으로 $T$시점의 주가의 기대값을 $E(S_T)=S_0e^{\mu T}$라고 표현해왔습니다. 왜 이런 차이가 발생하는 것일까요?

이를 이해하기 위해서는 먼저 우리가 가정한 주가모형을 잘 이해해야합니다. 연속복리수익률의 분포를 전개하기에 앞서, 우리는 시간 $\Delta t$에 대해서 주가의 수익률이 평균이 $\mu \Delta t$인 정규분포를 따른다고 가정하였습니다.

즉, 매우 작은 시간의 간격 $\Delta t$에서 주가수익률의 분포는 기대수익률과 동일하지만 이를 기간 $T$로 확장하게 되면, 그 사이의 수많은 $\Delta t$에 대해 수익률 $\mu$를 누적하게 됩니다.

이는 기하평균의 방식으로 주가수익률을 산출하는 것과 유사하며, 이에 따라 기간 $T$에 대해서 주가의 연속복리수익률의 평균은 $\Delta t$에 대해 $\mu$를 기하평균하여 산출한 $\mu-\frac{\sigma^2}{2}$가 됩니다. 산술평균한 결과인 $\mu$ 보다는 낮은 값입니다.
:::

## 15.4 Volatility

다음으로, 변동성을 나타내는 주가수익률의 표준편차 $\sigma$에 대해서 알아보겠습니다.

일반적으로 $\sigma$는 15% ~ 60% 수준의 값을 가지며, 이 의미는 주가의 연변동성이 15% ~ 60%라는 의미입니다.

앞서 강조하였던 것 처럼, 표준편차는 기간에 제곱근만큼 영향을 받으며 2년이라면 $\times\sqrt{2}$, 6개월이라면 $\times1/\sqrt{2}$ 등 시간 $\Delta t$에 대해 변동성은 $\sigma\Delta t$가 됩니다.

::: {.callout-note title="Estimating Volatility from historical data"}
과거 주가를 기반으로 주가의 연변동성 $\sigma$를 추정하는 경우, 일/주/월 단위의 주가를 통해 로그수익률을 산출한 다음, 표본표준편차를 산출하여 추정하게 됩니다.

즉, $s^2=\frac{1}{n-1}\sum_{k=1}^N(u_k-\bar{u})$를 이용해 $s$를 산출하고, 월 단위라면 $\hat{\sigma}=\sqrt{12}s$ 및 일 단위라면 $\hat{\sigma}=\sqrt{approx. 252}s$을 통해 연표준편차를 추정합니다.

이때, 표준편자의 표준오차는 $\frac{\hat{\sigma}}{\sqrt{2N}}$이 됩니다.
:::

## 15.5 ~ 6 The Black-Scholes-Merton differential equation

### The idea and Assumption

블랙-숄즈-머튼 미분방정식은 배당이 없는 주식에 대해서만 유효하며, 이항모형을 설명할 때 사용했던 무위험포트폴리오를 구성하는 방법과 유사한 방식을 활용할 것 입니다.

하나 다른 점은, 블랙숄즈 방정식에서는 순간적으로만 무위험포트폴리오 구성이 가능하며 이를 유지하려면 리밸런싱이 필요하다는 점 입니다.

먼저, 블랙숄즈 방정식의 7가지 가정입니다.

1. 주가수익률은 평균변화율이 $\mu$, 변동률이 $\sigma$인 GWP를 따른다.
2. 무차입공매도는 무한정으로 허용된다.
3. 거래비용 및 세금은 없으며, 모든 주식은 무한히 나눌 수 있다.
4. 파생상품의 만기까지 배당은 없다.
5. 무위험 차익거래 기회는 없다.
6. 주식의 거래는 연속적으로 이루어진다.
7. 무위험이자율 $r$이 존재하며, 모든 기간에 대해 상수이다.

### Derivation of the Black-Scholes-Merton Differential Equation

가정 1번에 따라 주가는 $d\,S=\mu\,S\,dt+\sigma\,S\,dz$를 따릅니다.

콜옵션의 가격을 $f$라고 하면, 이는 명백히 $S, \tau=T-t$의 함수이므로, 이토의 보조정리를 적용할 수 있습니다.

$$d\,f=(\frac{\partial f}{\partial S}\mu\,S+\frac{\partial f}{\partial t}+\frac{1}{2}\frac{\partial^2f}{\partial S^2}\sigma^2S^2)dt+\frac{\partial f}{\partial S}\sigma\,S\,dz$$

이 두가지 확률과정을 이용해서, $t$시점에서 무위험포트폴리오를 구성해보겠습니다.

1. 주식을 $\frac{\partial f}{\partial S}$만큼 매수
2. 주식 1주에 대한 콜옵션을 매도

이 포트폴리오를 $\Pi=\frac{\partial f}{\partial S}S-f$라고 하면, 랜덤워크 $dz$가 사라지므로, $t$시점에서 순간적인 포트폴리오의 변화분은 상수가 됩니다.

$$d\Pi=\frac{\partial f}{\partial S}\;d\,S-d\,f=-(\frac{\partial f}{\partial t}+\frac{1}{2}\frac{\partial^2f}{\partial S^2}\sigma^2S^2)dt$$

그렇다면, 이 포트폴리오는 순간적으로 무위험이므로 가정 5,6에 따라 $d\Pi=r\Pi\;d\,t$입니다.

이제 순차적으로 정리하면, 블랙숄즈 미분방정식을 얻을 수 있습니다.

$$r\Pi\;d\,t=d\Pi=-(\frac{\partial f}{\partial t}+\frac{1}{2}\frac{\partial^2f}{\partial S^2}\sigma^2S^2)dt$$

$$\Rightarrow\;\;r\Pi=-\frac{\partial f}{\partial t}-\frac{1}{2}\frac{\partial^2f}{\partial S^2}\sigma^2S^2$$

$$\Rightarrow\;\;-rf+r\frac{\partial f}{\partial S}S=-\frac{\partial f}{\partial t}-\frac{1}{2}\frac{\partial^2f}{\partial S^2}\sigma^2S^2$$

$$\therefore\;\;rf\;=\;\frac{\partial f}{\partial t}\;+\;rS\frac{\partial f}{\partial S}\;+\;\frac{1}{2}\frac{\partial^2f}{\partial S^2}\sigma^2S^2$$

::: {.callout-tip}
boundary conditions, perpetual derivatives, tradeable derivatives 등 교재 참조
:::

## 15.7 Risk-Neutral Valuation

블랙숄즈 미분방정식의 풀이는 (1) 물리학의 열 확산 방정식의 풀이 방법을 적용하여 편미분방정식의 특수해를 얻는 방법, (2) 위험중립세상을 가정하고 푸는 방법으로 나뉩니다.

여기서는 위험중립가정을 통해 최종적으로 공식을 유도해보겠습니다. 앞서 이항모형에서 살펴본 바와 같이, 블랙숄즈 방정식에 위험중립가정을 적용하더라도 결과값은 실제 세상과 동일하게 됩니다.

8. 모든 투자자는 Risk-neutral이며, 이에 따라 모든 자산의 기대수익률과 할인률은 무위험이자율 $r$이다.

::: {.callout-important}
블랙숄즈 미분방정식을 유도할 때, 순간적으로 무위험이 되는 포트폴리오를 구축하였습니다.

이 방법과 이항모형에서 활용한 전개방법은 동일하며, 위험중립가치평가의 방법도 동일하게 적용할 수 있습니다.

선도계약을 예시로 들어보겠습니다.

만기 $T$의 선도계약의 선도가격이 $K$이며, 현재의 선도계약의 가치가 $f$라면 선도계약의 만기 pay-off는 $S_T-K$입니다.

위험중립세상에서 선도계약을 가치를 구해보겠습니다. 모든 자산의 할인률은 $r$이므로, $f=e^{-rT}\hat{E}(S_T-K)=e^{-rT}\hat{E}(S_T)-Ke^{-rT}$입니다.

위험중립세상이므로 $\hat{E}(S_T)=S_0e^{rT(=\mu T)}$를 적용하면,

$$f=S_0-Ke^{-rT}$$

우리가 앞서 유도한 선도계약의 가치와 동일한 결과를 얻을 수 있습니다.
:::

## 15.8 Black-Scholes-Merton Pricing Formulas

$$c\;=\;S_0\,N(d_1)\;-\;K\,e^{-rT}\,N(d_2)$$

$$p\;=\;K\,e^{-rT}\,N(-d_2)\;-\;S_0\,N(-d_1)$$

$$where\;d_1=\frac{\ln(S_0/K)+(r+\sigma^2/2)T}{\sigma\sqrt{T}},\;\;d_2=d_1-\sigma\sqrt{T}$$

이제, 블랙숄즈 방정식의 가장 유명한 특수해인 유럽형 옵션의 가격공식에 대해서 알아보겠습니다.

먼저, 유럽형 콜옵션의 만기 pay-off는 $max(S_T-K,0)$입니다. 따라서 위험중립세상에서 유럽형 콜옵션의 현재가격은 아래와 같이 표현할 수 있습니다.

$$c=e^{-rT}\;\hat{E}[\,max(S_T-K,0)\,]$$

한편, $E(S_T)=S_0e^{rT}$이고 만기 T까지의 변동성은 $\sigma \sqrt{T}$이므로, 아래 정리를 이용하면 블랙숄즈 공식을 얻을 수 있습니다.

***By Theorem,***

$$c\;=\;S_0\,N(d_1)\;-\;K\,e^{-rT}\,N(d_2)$$

***By using Put-call parity $c-p=S_0-Ke^{-rT}$,***

$$p\;=\;K\,e^{-rT}\,N(-d_2)\;-\;S_0\,N(-d_1)$$

::: {.callout-important}
***Thm***

For lognormally distributed with the mean $m$ & volatility $w$,

$$E[\,max(V-K,0)\,]\;=\;E(V)\,N(d_1)\;-\;K\,N(d_2)$$

$where\;\;d_1=\frac{\ln{[E(V)/K]}+w^2/2}{w},\;\;d_2=d_1-w$

***Proof***

$E[max(V-K,0)]=\int_K^\infty (V-K)g(V)\;dV$

Let $Q=\frac{\ln{V}-m}{w}$, then $Q\sim\phi(0,1),\;h(Q)=\frac{1}{\sqrt{2\pi}}e^{-Q^2/2}$

We get,

$$E[max(V-K,0)]=\int_{(\ln{K}-m)/w}^\infty (e^{Qw+m}-K)h(Q)\;dQ$$

$$=\int_{(\ln{K}-m)/w}^\infty e^{Qw+m}h(Q)\;dQ-K\int_{(\ln{K}-m)/w}^\infty h(Q)\,dQ$$

Note that,

$$e^{Qw+m}h(Q)=\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}(Q^2-2wQ-2m)}=\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}((Q-w)^2-w^2-2m)}$$

$$=e^{(w^2+2m)/2}\times\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}(Q-w)^2}=e^{(w^2+2m)/2}\;h(Q-w)$$

Therefore,

$$E[max(V-K,0)]=e^{(w^2+2m)/2}\;\int_{(\ln{K}-m)/w}^\infty h(Q-w)\;dQ-K\int_{(\ln{K}-m)/w}^\infty h(Q)\,dQ$$

It is obvious that $m=\ln E(V)-\frac{w^2}{2}$ & $1-N(x)=N(-x)$,

Let $d_1=-\frac{\ln K-m}{w}+w=\frac{\ln [E(V)/K]+w^2/2}{w}$

Now,

$$E[\,max(V-K,0)\,]\;=\;E(V)\,N(d_1)\;-\;K\,N(d_2),\;\because\; e^{(w^2+2m)/2}=e^{\ln E(V)}=E(V)$$
:::