# Chapter 5 {.unnumbered}

선도 및 선물 가격의 결정요인

*(Determination of Forward and Futures Prices)*

## 5.1 투자자산 vs. 소비자산

선도 및 선물계약에 있어서 기초자산이 투자자산인지 소비자산인지 구분하는 것은 매우 중요합니다. 이 챕터에서는 투자자산을 중심으로 선도/선물가격과 기초자산 가격간의 관계를 차익거래를 이용하여 서술할 예정입니다.

- 투자자산(investment asset) : 주식,채권, 금, 은과 같은 투자목적으로 주로 거래되는 자산

- 소비자산(consumption asset) : 원유, 원자재 등 주로 생산 또는 소비목적으로 거래되는 자산

::: {.callout-note}
어떠한 자산이 반드시 투자자산이나 소비자산에 속하는 것은 아닙니다. 누군가는 원유를 투자 목적으로 거래할 수 있으며, 생산목적으로 은과 같은 귀금속을 거래하기도 합니다. 주로 거래되는 목적에 따른 단순 분류임을 유의하시기 바랍니다.
:::

## 5.2 공매도

**공매도란 현재 가지고 있지 않은 자산을 빌려서 파는 행위**를 말합니다. 주로 현재시점에서 자산을 빌려서 미리 팔고, 추후 자산을 시장가격에 구매해서 값는 식으로 이루어집니다.

차익거래 메커니즘을 통해 선도/선물가격을 설명할 때 공매도가 자주 사용되며, 공매도를 실행할 때 자산을 빌리는 데 드는 비용(대차비용)이 존재하고 때때로 공매도가 불가능한 투자자산도 존재하지만, 대체로 **공매도가 가능하고 별도의 비용이 들지않는다는 가정**을 포함합니다.

::: {.callout-note title="공매도와 규제"}
과거부터 공매도는 주식시장의 과도한 하락을 초래한다는 부정적인 인식 및 효과로 인해 규제되어왔습니다.

최초로 1938년 업틱룰(uptick-rule)이 소개되었는데, 이는 공매도 호가를 제출할 때 현재 매도최우선호가보다 높은 호가에 제출해야하는 규제로, 공매도로 인해 시세하락변동이 유발되지 않도록 하는 규제입니다.

미국의 경우 2007년 업틱룰이 폐치되고 대체 규제(alternative uptick rule)이 소개되었으며, 이는 주식이 당일 10%이상 하락하였을 때, 그날과 다음날까지 업틱룰을 적용하는 제도입니다

또한, 때때로 공매도는 금융시장이 불안정할때 금지되어 왔으며, 미국에서는 2008년 서프프라임 금융위기때 일시적으로 금지하였습니다. 국내의 경우 금융위기 및 코로나위기('20년), 경기침체('23.11~'24.3월현재 지속) 등 공매도를 일시적으로 중단하고 있습니다.
:::

## 5.3 Assumptions and Notation

선도/선물가격을 결정할 때, 아래의 4가지 사항이 참이라고 가정합니다. 실제 거래규모가 큰 일부 기관투자자에게만 아래 가정이 적용되더라도 차익거래 메커니즘이 작동하는 데에 문제는 없습니다.

1. 모든 시장참여자는 거래비용이 0이다.
2. 모든 시장참여자는 모든 거래순이익에 대해 동일한 세율을 적용받는다.
3. 모든 시장참여자는 무위험이자율에 무한대로 자금을 빌리거나 빌려줄 수 있다.
4. 모든 시장참여자는 차익거래 기회가 생기면 이를 이용한다.

## 5.4 투자자산에 대한 선도가격

가장 간단한 선도계약을 예시로 들어보면, 보관비용이 없고 현금흐름을 발생시키지 않는 기초자산에 대한 선도계약으로, 배당이 없는 주식 또는 무이표채에 대한 선도를 예시로 들 수 있습니다.

현재 시점에서 3개월 뒤 만기가 도래($T$)하는 선도계약의 현재가격을 $F_0$, 기초자산의 현재가격을 $S_0$, 3개월 무위험이자율을 $r$이라고 할 때, 현재시점의 지출 없이 $T$시점에 기초자산을 보유하는 방법은 두 가지로 나눌 수 있습니다.

1. 선도계약 매수하여 T시점에 선도계약가격으로 기초자산을 매수
2. 무위험이자율로 자금을 빌려 기초자산을 매수하고 T시점까지 보유

위 두가지 방법을 현재시점에 실행하고, 만기 T시점까지의 현금흐름은 다음과 같습니다.

$1.\;만기\;T시점에\;선도계약가격\;F_0\;지출$

$2.\;현재시점에\;기초자산가격\;S_0\;지출,\;만기시점에\;이자비용\;S_0(e^{rT}-1)\;지출$

위 두가지 현금흐름은 정확히 동일해야하므로, 선도/선물가격은 다음과 같습니다.

$$F_0=S_0e^{rT}$$

만약, 이 등식이 성립하지 않는다면 차익거래가 발생합니다.

$F_0>S_0e^{rT}$인 경우, 현재시점에 ***1.선도계약을 매도***하고 ***2. 무위험이자율로 자금을 빌려 기초자산을 매수***하면, T시점에 $F_0-S_0e^{rT}$만큼 무위험 차익거래가 가능합니다.

반대인 경우, 현재시점에 ***1.선도계약을 매수***하고 ***2. 기초자산을 공매도하고 매도대금을 무위험이자율에 투자***하면, T시점에 $S_0e^{rT}-F_0$만큼 무위험 차익거래가 가능합니다.

한편, 실제 금융시장에서 공매도는 모든 기초자산에 대해 가능한 것이 아니고, 대게 비용이 발생합니다. 따라서 공매도가 제한적인 경우 선도가격이 저평가되었을 때 차익거래는 불가능할 수도 있습니다.

그러나, 기초자산을 본래 보유하고 있던 투자자는 현재시점에 ***1.선도계약을 매수***하고 ***2. 보유한 기초자산 매도하고 매도대금을 무위험이자율에 투자***하면, T시점에 $S_0e^{rT}-F_0$만큼 무위험 차익거래가 가능하기 때문에, **공매도가 제한적이더라도 대부분의 경우에 위의 수식이 성립**합니다.

::: {.callout-warning title-"Kidder Peabody's Mistake"}
투자은행들은 종종 이표채의 현금흐름을 각각 개별 zero-coupon 채권으로 전환하는 strip이라는 기법을 사용합니다.

Kidder Peabody의 트레이더 Jett는, 컴퓨터 계산 결과 채권을 strip하여 각각을 선도계약을 통해 매도하면 약 \$100m이익을 얻을 수 있다는 차익거래 기회를 포착하고 거래를 실행하였습니다.

그러나, Jett는 채권을 매수하여 strip하는 거래비용을 간과하였고, 이익 대신 총 \$330m의 손실을 회사에 미치고 말았습니다.
:::

## 5.5~6 기초자산의 현금흐름

지금까지는 배당이나 이표 등 현금흐름이 발생하지 않는 기초자산에 대해서 알아봤습니다. 만약 현금흐름이 발생하지만, 기초자산의 현재시점부터 선도/선물 만기까지의 모든 현금흐름을 정확하게 알고있다면, 동일한 방식으로 선도/선물계약 평가가 가능합니다.

1. 선도계약 매수하여 T시점에 선도계약가격으로 기초자산을 매수
2. 무위험이자율로 자금을 빌려 기초자산을 매수하고 T시점까지 보유

#### ***Discrete***{#sec-5.6dis}

$T_1$시점에 기초자산에 $I$만큼 현금흐름이 발생한다면, 두 경우의 만기까지 현금흐름은 아래와 같습니다.

$1.\;만기\;T시점에\;F_0\;지출$

$2.\;현재시점에\;S_0\;지출,\;T_1시점에\;수익\;I\;발생,\;만기시점에\;이자비용\;S_0(e^{rT}-1)\;지출$

이를 정리하면,

$$F_0=S_0e^{rT}-Ie^{r(T-T_1)}=(S_0-I_0)e^{rT}\;where\;I_0=Ie^{-rT_1}$$

#### ***Continuous*** {#sec-5.6con}

기초자산의 현재부터 만기까지 평균적으로 연속복리수익률 $q$만큼의 현금흐름이 발생한다면, 만기시점에 $S_0$를 보유하기 위해 현재 $S_0e^{-qT}$만큼만 매수하면 됩니다.

1. 선도계약 매수하여 T시점에 선도계약가격으로 기초자산을 매수
2. 무위험이자율로 자금을 $S_0e^{-qT}$만큼만 빌려 기초자산을 매수하고 T시점까지 보유

$1.\;만기\;T시점에\;F_0\;지출$

$2.\;현재시점에\;S_0e^{-qT}\;지출,\;만기시점에\;이자비용\;S_0e^{-qT}(e^{rT}-1)\;지출$

$$즉,\;F_0=S_0e^{(r-q)T}$$

## 5.7 선도계약의 가치

은행이나 기관입장에서 과거에 이루어진 선도계약의 가치평가는 매우 중요합니다. 실제로 은행 등 기관에서는 선도계약의 가치를 매일매일 평가(Marking to Market)하고 있습니다.

**선도계약의 가치는 계약을 중도에 청산하고자 하는 투자자가 얻게되는 손익**이므로, 기존의 선도계약과 가치가 "0"인 선도가격(즉, 현재시점의 선도가격)의 현금흐름을 비교하는 방법을 사용합니다.

과거 선도계약의 가격(delivery price)가 $K$, 현재 선도계약의 균형가격이 $F_0$, 무위험이자율이 $r$이면 두 계약 만기 $T$시점의 지출은 각각 $K$, $F_0$입니다. 현재 선도계약은 가치가 "0"이므로 선도계약의 미래가치는 매수의 경우 $F_0-K$, 매도의 경우 $K-F_0$가 됩니다.

이를 정리하면 선도계약의 가치 $f$는 다음과 같습니다.

$$f_{long}=(F_0-K)e^{-rT}\;or\;f_{short}=(K-F_0)e^{-rT}$$

위에서 다룬 선도가격 $F_0$를 여기에 적용하면, 다음과 같이 표현할 수 있습니다.

$$f_{long}=(F_0-K)e^{-rT}=S_0-Ke^{-rT}=S_0-I_0-Ke^{-rT}=S_0e^{-qT}-Ke^{-rT}$$

## 5.8 선도가격=선물가격 ?

선물가격과 선도가격은 대체로 동일하지만, **선물의 일일정산으로 인해 차이가 발생**합니다. 선도계약을 평가할 때, 우리는 현재와 만기시점까지 발생하는 현금흐름을 비교하였습니다.

선도는 만기까지 현금흐름이 발생하지않고 만기에 기초자산을 선도가격에 인수도함으로써 마무리됩니다. 그러나 선물가격은 일일정산이 존재하므로 매일매일 기초자산의 가격변동에 따른 현금흐름이 발생합니다. 다시 말해, **선물 매수자의 기준으로 기초자산 가격이 상승하면 (+) 현금흐름이, 가격이 하락하면 (-) 현금흐름**이 발생합니다.

이 경우, 현금흐름 발생에 따라 각 현금흐름의 미래가치를 계산하여 비교하게되는데 여기서 선도와 선물의 차이가 발생하게 됩니다. 일반적으로 주가의 향후 방향성은 예측할 수 없으므로 현재시점에 일일정산으로 인한 평가가격 차이는 없으나, 만약 **이자율과 주가간에 상관관계가 존재한다면** 이야기가 달라집니다.

**이자율과 주가가 양의 상관관계**인 경우, 주가 상승 및 이자율 상승시 선물 매수자에게 이익이 발생하고 이를 미래가치로 평가할 때 이자율 상승으로 인해 미래가치가 크게 상승하므로 선물 보유자에게 유리합니다. 주가 하락 및 이자율 하락시에는 선물 매수자의 손실을 미래가치로 평가할 때 손실이 적게 상승하므로 **선물 보유자에게 유리**합니다.

반대로, **이자율과 주가가 음의 상관관계**인 경우, 주가 상승 시 선물 매수자의 이익이 낮게 상승하고 주가 하락시 손실이 크게 상승하므로 **선물 보유자에게 불리**합니다.

즉, **주가와 이자율간 상관관계**에 따라 선도가격과 선물가격의 차이가 결정되며, 일반적으로 **양의 상관관계일 때 선물가격이 높게, 음의 상관관계일 때 선도가격이 높게 형성**됩니다. 이러한 차이는 만기까지의 잔존기간이 길수록 커집니다.

## 5.9~12 Cost of Carry 및 다양한 선도/선물가격 {#sec-costofcarry}

만기 현금흐름 비교를 통해 차익거래가 발생하지 않는 선도/선물가격을 결정하는 방법을 ***보유비용모형(The Cost of Carry)***이라고 합니다.

지금까지 기초자산을 만기 T에 보유하는 방법으로 *1. 선도/선물 매수*, *2. 자금 조달 및 현물 매수*로 나누어 비교하였는데, 이 방식을 선도/선물 매수자입장에서 생각해보면 선도/선물계약을 만기까지 보유하는 동안 실제로 현물을 보유하지 않으므로, **현물에서 발생하는 수익은 선도/선물 매수자에게 불리**하게, **현물을 보관하는데에 드는 비용은 선도/선물 매수자에게 유리**하게 작용합니다.

즉, **선도/선물가격**은 기초자산의 현재가격에 만기 $T$시점까지의 **기초자산에서 발생하는 수익을 차감하고 기초자산을 보관하는 비용을 가산**하여 결정됩니다.

$$F_0=S_0-Benefit+Cost=S_0e^{(cost-yield)T}\;(Generalized)$$

투자자산에서 주식과 채권 등의 보관비용은 현금의 기회비용인 무위험이자율에 해당하므로, 일반적으로 $S_0e^{rT}$로 표현된다고 해석할 수 있습니다.

### 주가지수선물

보유비용모형을 통해 주가지수선물 가격을 평가할 때, 고려해야할 보유비용은 현금의 기회비용인 $r$ 및 보유수익은 배당률 $d$입니다.

$$Index\;Futures\;F_0=S_0e^{(r-d)T}$$

#### 지수차익거래

주가지수선물도 마찬가지로 이 등식이 성립하지 않는다면 차익거래가 발생합니다. $F_0>S_0e^{(r-d)T}$인 경우, 선물을 매도하고 자금을 빌려 주가지수 복제 포트폴리오를 매수함으로써 지수차익거래를 할 수 있습니다. 반대로 $F_0<S_0e^{(r-d)T}$ 인 경우 선물을 매수하고 주가지수 복제 포트폴리오를 공매도함으로써 지수차익거래를 할 수 있습니다.

### 선도환, 선물환 및 통화선물

해외통화의 현재환율을 $S_0$, 선도환율을 $F_0$, 자국과 해외의 무위험이자율을 각각 $r,\;r_f$라고 한다면, 만기 $T$시점에 해외통화를 보유하는 두가지 방법은,

1. Currency Forward or Futures를 $F_0$에 매수
2. 자국 통화를 $S_0e^{-r_fT}$만큼 빌려 해외 통화를 매입하고 만기까지 보유

만기시점까지의 현금흐름을 살펴보면,

$1. 만기시점에 F_0e^{r_fT} 지출$

$2. 현재시점에 S_0e^{-r_fT} 지출, 만기시점에 자국통화 이자비용 S_0e^{-r_fT}(e^{rT}-1)$

즉, @sec-5.6con 과 동일한 방식을 적용하여 $Currency,\;F_0=S_0e^{(r-r_f)T}$를 도출할 수 있습니다. 이는, 선도환 및 통화선물을 거래할 때, 기초자산의 보유비용은 자국의 무위험이자율이며 기초자산의 보유수익은 해외통화의 무위험이자율임을 뜻합니다.

### 상품선물

귀금속이나 원자재 등 Comodity는 일반적으로 현물을 보유하는데에 보관비용이 발생합니다. 현재시점부터 만기까지의 보관비용을 $U$만큼 선불지급한다고 하면 해당 Comodity를 만기 T시점에 보유하는 방법은,

1. Comodity Forward or Futures를 $F_0$에 매수
2. 자금을 $S_0+U$만큼 빌려 현물을 $S_0$에 매수하고 보관비용을 $U$만큼 지급

만기시점까지의 현금흐름은,

$1. 만기시점에 F_0 지출$

$2. 현재시점에 S_0+U 지출, 만기시점에 자국통화 이자비용 (S_0+U)(e^{rT}-1)$

즉, @sec-5.6dis 과 동일한 방식으로 $F_0=(S_0+U)e^{rT}$를 도출할 수 있습니다. 만약 $U$를 연속복리이자율을 적용한 $S_0e^{uT}$로 표현한다면, $F_0=S_0e^{(r+u)T}$라 할 수 있습니다.

추가적으로, convenience yield가 있는 상품의 경우 그 수익률을 $y$라 한다면 최종적으로 다음과 같이 나타낼 수 있습니다.

$$Comodity,\;F_0=S_0e^{(r+u-y)T}$$

## 5.13 실물인수도에 따른 옵션, Delivery Options

일부의 선물계약과 선도계약은 만기시점에 실제로 기초자산과 매수대금을 주고 받는 실물인수도를 최종결제방식으로 채택합니다. 이때, 선도계약은 인수도 시점에 대한 것이 명확하게 계약시점에 정해지지만, **선물계약은 일반적으로 매도자가 언제 기초자산을 인도할지에 대한 선택권**을 가지고있습니다. 정해진 인수도기간 중에, 언제 인수도가 이루어지냐에 따라서 선물계약의 가치평가에 영향을 미치게 되는 것 입니다. 물론 대부분의 선물이 만기 전 반대거래로 청산이 이루어진다고는 하지만, 알아두고 갈 필요는 있습니다.

위에서 살펴본 바와 같이, 일반적으로 선물가격은 $S_0e^{rT}$로 결정되며 이는 잔존만기에 따른 증가함수입니다. 이는 @sec-costofcarry 관점에서 볼 때 기초자산에 보유비용이 발생한다는 의미로, **선물가격이 현물가격보다 높게 형성**된다면 선물 매도자입장에서는 **인수도기간 중 가능한 빨리 인수도를 할 유인**이 생긴다는 것을 의미합니다.

반대로, **선물가격이 현물가격보다 낮게 형성**된다면 시장상황이 기초자산에 보유이익이 발생한다는 의미로, 선물 매도자입장에서는 **가능한 늦게 인수도를 할 유인**이 생긴다는 것을 의미합니다.

## 5.14 선물가격과 미래 현물가격의 기대값

현재까지 **선물가격에 관한 내용은 미래 현물가격에 대한 시장의 기대가 반영된 값이 아닌, 단순히 No-Arbitrage-Rule에 따라 산출된 수학적인 값**입니다.

여기에 현물가격에 대한 시장의 기대심리 또는 기대값이 반영된다면 선물가격은 달라질 것 입니다. 시장에서 **현물이 향후 상승할 것으로 예상**된다면 **선물은 이론가격보다 높게 형성**될 것이고, **현물이 하락할 것으로 예상**된다면 **선물은 이론가격보다 낮게 형성**될 것 입니다.

### Keynes and Hicks

만약 선물시장에서 위험관리를 하고자 하는 투자자는 선물 매도를 주로 하고, 방향성 투자를 하고자하는 투자자는 선물 매수를 주로 하는 경우, 선물가격은 현물가격의 미래 기대값보다 낮게 형성될 것이라고 말했습니다.

방향성 투자자는 선물을 매수할 때 위험에 대한 보상심리로 평균 이상의 수익률을 기대하기때문에 미래의 현물 기대값보다 낮은 가격에 선물을 매수하며, 위험관리 투자자는 자신의 위험을 감소시키는 것에 대한 대가로 일정 비용을 치루는 것을 감수하기 때문입니다.

따라서, 만약 위험관리 투자자가 선물 매수를 주로하고 방향성 투자자가 선물 매도를 주로 한다면 선물가격이 현물가격의 기대값보다 낮게 형성될 것 입니다.

### Risk and Return

최근의 접근방법은 선물가격과 현물가격의 관계를 리스크 대비 기대수익으로 설명하고 있습니다. CAPM 등에서 투자자산의 리스크가 높다면 보다 높은 기대수익률을 가지고 있어야 합니다. @sec-CAPM

#### 선물포지션의 리스크

현재 선물가격을 $F_0$, 만기시점의 현물가격을 $S_T$, 무위험이자율을 $r$이라 할 때, 향후 현물가격이 상승할 것을 기대하고 선물 매수에 투자하는 방향성 투자자를 생각해봅시다. ($S_T>F_0$ 기대)

이를 위해 현재 $F_0$에 선물을 매수하고 자금을 $F_0e^{-rT}$만큼 무위험이자율 $r$에 투자하여, 만기 $T$시점에 $F_0$에 현물을 인수도받아 즉시 $S_T$에 판다고 하고, 일일정산 및 거래비용 등은 없다고 가정하면 투자자의 현금흐름은 다음과 같습니다.

$현재시점\;:\;-F_0e^{-rT}$

$만기시점\;:\;+S_T$

이 때, 투자자의 선물포지션에 대한 기대수익률은 $k$이며 현재시점의 선물계약의 가치가 0이라고 하면, 다음과 같이 정리할 수 있다.

$$-F_0e^{-rT}+E[S_T]e^{-kT}\;\Rightarrow\;F_0=E[S_T]e^{(r-k)T}$$

여기서 $k$는 기초자산의 *systematic risk*에 따라 달라지며, 이에 대한 관계는 아래와 같습니다.

|Underlying asset|$k\sim r$|$F_0\sim S_T$|States|
|:--------------:|:-------:|:---------:|:-----------:|
|No systematic risk|$k=r$|$F_0=E[S_T]$|-|
|(+) Systematic risk|$k>r$|$F_0<E[S_T]$|Contango|
|(-) Systematic risk|$k<r$|$F_0>E[S_T]$|**Normal backwardation**|

특히, $k=r\;\Rightarrow\;F_0=E[S_t]$인 경우, 선물가격은 현물의 미래 기대값에 대한 불편추정량임을 의미합니다.